### ISSUE TITLE
Input: Percent sign is getting trimmed when using the percentage mask and allow decimal, when more than two characters are typed after the decimal

### ISSUE THREAD

**Issue by shani-terminus** [GetTerminus/terminus-ui#1177] opened 2018-12-21 15:17 UTC
When using the percentage mask and allow decimal, only two characters are allowed past the decimal point. Typing a third character will trim that character (desired) as well as the % (not desired).

Affects both sanitized and not sanitized, affects 9.x and 10.x versions

**Comment by benjamincharity** [comment] 2019-02-18 12:10
Duplicate of #1167

**Closed by benjamincharity** 2019-02-18 12:10 UTC
Labels: Focus: component, Needs: exploration, P3: Important, Target: latest, Type: bug
